### PR TITLE
Bugfix on the ontology wizard

### PR DESCRIPTION
**Pull request by mmateva**
In this version, repositories can be connected with no credentials.
For example, repository http://molto.ontotext.com/sparql should work directly.
Please have a look.

### CODE REVIEW

**Comment by johnjcamilleri** [comment]
After pulling this code and opening Eclipse, I get an error in `MANIFEST.MF`:

```
Description: Package 'com.ontotext.molto.repositoryHelper' does not exist in this plug-in
Resource: MANIFEST.MF
Path: /org.grammaticalframework.eclipse.ontology-grammar/META-INF
Location: line 15
Type: Plug-in Problem
```

This happens whether I use the new `molto-repository-helper-1.0-SNAPSHOT.jar` or the original `molto-repository-helper-1.0.jar`. (By the way, we should probably stick with just one of these and remove the other).

**Comment by mmateva** [comment]
Yes, it should be molto-repository-helper-1.0-SNAPSHOT.jar
I am not sure how it got mixed up...

**Comment by johnjcamilleri** [comment]
Ok, I have avoided the issue by removing the `Export-Package` stuff in the manifest file. See the new commit 72c16ad.
Other than that, I can successfully connect to the repository as you specified, thanks for that.

**Comment by mmateva** [comment]
Oh, np, that should have been done long time ago.

**Pull request merged**
